"""Paths, school list and seasons for the pipeline, the hand-edited input loaders, and the site rules.

The site rules are hand-confirmed facts about how each school's athletics site behaves. They live in
data/inputs/site_rules.csv (edit that file, not this one); this module loads and checks the CSV the first time
a rule table such as config.KNOWN_UNAVAILABLE is used, so importing config never needs the file.
"""
import csv
import functools
import os
from collections import namedtuple
from datetime import date

import pandas as pd

VERBOSE = False  # set by --verbose; per-item progress goes through note(), summaries and warnings through print()


def note(*args):
    if VERBOSE:
        print(*args)


# A season is named for the calendar year it starts in (2016 is 2016-17). The current season comes from today's date and
# nothing needs editing each year: seasons start in August, so it is 2026 from August 2026 through July 2027, then 2027.
FIRST_YEAR = 2016
SEASON_STARTS_IN_MONTH = 8


def _current_season(today=None):
    if today is None:
        override = os.environ.get("IVY_TODAY")  # YYYY-MM-DD: for tests, or to see what a run in September would do
        today = date.fromisoformat(override) if override else date.today()
    return today.year if today.month >= SEASON_STARTS_IN_MONTH else today.year - 1


CURRENT_YEAR = _current_season()
YEARS = list(range(FIRST_YEAR, CURRENT_YEAR + 1))
# Older seasons discovery tries when a page has nothing for the current season, so teams that were later cut are still found.
PROBE_YEARS = [CURRENT_YEAR - 1, 2021, 2019, YEARS[0]]

# Ivy League athletics site hosts.
bases = {
    "school": ["Brown", "Columbia", "Cornell", "Dartmouth", "Harvard", "Penn", "Princeton", "Yale"],
    "site_page": ["brownbears.com", "gocolumbialions.com", "cornellbigred.com", "dartmouthsports.com", "gocrimson.com", "pennathletics.com",
                  "goprincetontigers.com", "yalebulldogs.com"]
}
bases_df = pd.DataFrame(bases)

# Layout: <root>/pipeline (code), <root>/data (inputs + outputs), <root>/docs (published site); anchored to this file.
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT_DIR, "data")
INPUTS_DIR = os.path.join(DATA_DIR, "inputs")  # hand-edited
STATE_DIR = os.path.join(DATA_DIR, "state")    # kept by the pipeline; commit it (except the scrape log)
AUDIT_DIR = os.path.join(DATA_DIR, "audit")    # generated by checks.py audit; gitignored
ROSTERS_DIR = os.path.join(DATA_DIR, "rosters")
GEO_DIR = os.path.join(DATA_DIR, "geo-rosters")
DOCS_DIR = os.path.join(ROOT_DIR, "docs")
# rosters/ is created by `rosters.py pull`, not on import.

# Hand-edited inputs.
REFERENCE_PATH = os.path.join(INPUTS_DIR, "sport_page_reference.xlsx")
FIXES_PATH = os.path.join(INPUTS_DIR, "hometown_fixes.csv")
NAME_FIXES_PATH = os.path.join(INPUTS_DIR, "name_fixes.csv")
REGIONS_PATH = os.path.join(INPUTS_DIR, "regions.csv")
RULES_PATH = os.path.join(INPUTS_DIR, "site_rules.csv")

# Pipeline state.
AVAILABILITY_CACHE_PATH = os.path.join(STATE_DIR, "school_sport_availability.csv")
SCRAPE_LOG_PATH = os.path.join(STATE_DIR, "scrape_log.csv")
HOMETOWN_CACHE_PATH = os.path.join(STATE_DIR, "hometown_cache.csv")
HOMETOWN_FAILED_PATH = os.path.join(STATE_DIR, "hometown_failed.csv")
INFERRED_LOG_PATH = os.path.join(STATE_DIR, "inferred_seasons.csv")
SEASON_STATUS_PATH = os.path.join(STATE_DIR, "season_status.csv")


@functools.cache
def sport_refs():
    """sport_page_reference.xlsx (columns sport, sport_page), read on first use so importing this module never needs it."""
    if not os.path.exists(REFERENCE_PATH):
        raise FileNotFoundError(f"Could not find sport_page_reference.xlsx at {REFERENCE_PATH}.")
    return pd.read_excel(REFERENCE_PATH)


def _csv_rows(path):
    """[(line number, [fields])] of a hand-edited CSV, read as real CSV so a quoted comma stays in one field."""
    if not os.path.exists(path):
        return []
    with open(path, newline="", encoding="utf-8-sig") as f:
        reader = csv.reader(f)
        next(reader, None)
        return [(reader.line_num, row) for row in reader if any(cell.strip() for cell in row)]


def _fix_rows():
    return _csv_rows(FIXES_PATH)


def fix_problems():
    """What is wrong with data/inputs/hometown_fixes.csv in a way that makes a fix silently do nothing (or do the wrong thing)."""
    problems, seen = [], {}
    for line, row in _fix_rows():
        if len(row) != 2:
            problems.append(f"line {line}: {len(row)} fields instead of 2, so this fix is ignored (a hometown with a comma in it must be in quotes, like \"Hartford, Conn.\")")
            continue
        hometown, corrected = row
        if not hometown.strip() or not corrected.strip():
            problems.append(f"line {line}: a blank cell, so this fix is ignored")
            continue
        if hometown != " ".join(hometown.split()) or corrected != " ".join(corrected.split()):
            problems.append(f"line {line}: extra or odd spaces in {hometown!r} -> {corrected!r}; a space that is not in the roster text means it never matches")
        if hometown == corrected:
            problems.append(f"line {line}: {hometown!r} is corrected to itself")
        if hometown in seen and seen[hometown] != corrected:
            problems.append(f"line {line}: {hometown!r} was already corrected on line {seen[hometown][1]} to a different text (this later row wins)")
        seen[hometown] = (corrected, line)
    return problems


def name_fix_problems():
    """What is wrong with data/inputs/name_fixes.csv (columns school, name, corrected) in a way that makes a fix silently do nothing."""
    problems, seen = [], {}
    schools = set(bases_df["school"])
    for line, row in _csv_rows(NAME_FIXES_PATH):
        if len(row) != 3:
            problems.append(f"line {line}: {len(row)} fields instead of 3 (school, name, corrected), so this fix is ignored")
            continue
        school, name, corrected = row
        if school not in schools:
            problems.append(f"line {line}: unknown school {school!r} (one of {', '.join(sorted(schools))}), so this fix is ignored")
        elif not name.strip() or not corrected.strip():
            problems.append(f"line {line}: a blank cell, so this fix is ignored")
        elif name != " ".join(name.split()) or corrected != " ".join(corrected.split()):
            problems.append(f"line {line}: extra or odd spaces in {name!r} -> {corrected!r}; a space that is not in the roster text means it never matches")
        elif name == corrected:
            problems.append(f"line {line}: {name!r} is corrected to itself")
        if (school, name) in seen and seen[(school, name)] != corrected:
            problems.append(f"line {line}: {school} {name!r} was already corrected to a different name (this later row wins)")
        seen[(school, name)] = corrected
    return problems


# Hand-made name corrections: {(school, name as the roster has it): corrected name}, for a name the source page got wrong
# (a lost accent, a typo). Applied when the roster files are written, so every later file carries the corrected name.
def load_name_fixes():
    schools = set(bases_df["school"])
    return {(row[0], row[1]): row[2] for _, row in _csv_rows(NAME_FIXES_PATH)
            if len(row) == 3 and row[0] in schools and row[1].strip() and row[2].strip()}


# Hand-made hometown corrections: {original text: corrected text}. Rows that are not exactly two non-blank fields are skipped (see fix_problems).
def load_fixes():
    return {row[0]: row[1] for _, row in _fix_rows() if len(row) == 2 and row[0].strip() and row[1].strip()}



# ───────────────────────────── site rules (from data/inputs/site_rules.csv) ─────────────────────────────
# CSV columns: school, sport_page, rule, year, value, note
#   school is a school name, or "*" for rules that apply to every school; sport_page is the URL-style sport name
#   (e.g. womens-volleyball). Blank lines and lines whose school starts with "#" are ignored.
_RULE_FORMS = ("bare", "dash")
_RULE_COLUMNS = ["school", "sport_page", "rule", "year", "value", "note"]

# rule -> (school, year, value)   school: "one" = names one school, "all" = must be "*"   year/value: "req" or "no" (must be blank)
_RULE_SPECS = {
    "slug_alias":     ("all", "no",  "req"),  # value = another URL name to try for sport_page
    "spring_season":  ("all", "no",  "no"),
    "skip_bare_year": ("all", "no",  "no"),
    "prefer_bare":    ("one", "no",  "no"),
    "prefer_dash":    ("one", "req", "no"),   # year = last season tried dash-first
    "form_through":   ("one", "req", "req"),  # value = bare|dash, used through `year`
    "form_from":      ("one", "req", "req"),  # value = bare|dash, used from `year` on, every later season too
    "missing_season": ("one", "req", "no"),
    "first_year":     ("one", "req", "no"),
    "unavailable":    ("one", "no",  "no"),   # the note holds the reason (required)
    "slug_override":  ("one", "no",  "req"),  # value = the only slug to try
    "combined_page":  ("one", "no",  "no"),
    "cleanup_exempt": ("all", "no",  "no"),
}
# Rules where one (school, sport_page) may appear only once.
_RULE_SINGLE_VALUED = {"prefer_dash", "first_year", "slug_override", "unavailable", "form_from"}
_RuleRow = namedtuple("_RuleRow", "line school sport rule year value note")

# The tables other modules read as config.<NAME>.
_RULE_TABLE_NAMES = (
    "SPORT_SLUG_ALIASES", "SPRING_SEASON_SPORTS", "SKIP_BARE_YEAR_SPORTS", "SCHOOL_PREFERS_BARE_YEAR",
    "SCHOOL_PREFERS_DASH_YEAR", "SCHOOL_FORM_THROUGH", "SCHOOL_FORM_FROM", "KNOWN_MISSING_SEASONS", "PROGRAM_FIRST_YEAR",
    "KNOWN_UNAVAILABLE", "SCHOOL_SLUG_OVERRIDES", "KNOWN_COMBINED_PAGE", "NEUTRAL_ENTRY_CLEANUP_EXEMPT",
)


def _read_rules(path):
    rows = []
    with open(path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        missing = [c for c in _RULE_COLUMNS if c not in (reader.fieldnames or [])]
        if missing:
            raise ValueError(f"{path}: missing column(s) {missing}")
        for rec in reader:
            if not any((v or "").strip() for v in rec.values()):
                continue
            get = lambda k: (rec.get(k) or "").strip()
            if get("school").startswith("#"):
                continue
            rows.append(_RuleRow(reader.line_num, get("school"), get("sport_page"), get("rule"),
                                 get("year"), get("value"), get("note")))
    return rows


def _check_rules(raw, valid_schools):
    """Return (rows with integer years, list of error strings)."""
    rows, errors = [], []
    seen, unique = set(), {}
    for r in raw:
        where = f"line {r.line}"
        spec = _RULE_SPECS.get(r.rule)
        if spec is None:
            errors.append(f"{where}: unknown rule {r.rule!r}")
            continue
        school_kind, year_kind, value_kind = spec
        problems = []
        if not r.sport:
            problems.append("sport_page is empty")
        if school_kind == "all":
            if r.school != "*":
                problems.append('school must be "*" for this rule')
        elif r.school in ("", "*"):
            problems.append("school must name one school")
        elif r.school not in valid_schools:
            problems.append(f"unknown school {r.school!r}")
        year = None
        if year_kind == "req":
            if r.year.isdigit():
                year = int(r.year)
            else:
                problems.append("year must be a whole number")
        elif r.year:
            problems.append("year must be blank for this rule")
        if value_kind == "req":
            if not r.value:
                problems.append("value is required")
            elif r.rule in ("form_through", "form_from") and r.value not in _RULE_FORMS:
                problems.append(f"value must be one of {_RULE_FORMS}")
        elif r.value:
            problems.append("value must be blank for this rule")
        if r.rule == "unavailable" and not r.note:
            problems.append("note (the reason) is required")
        if problems:
            errors.extend(f"{where}: {p}" for p in problems)
            continue

        row = r._replace(year=year)
        full = (row.rule, row.school, row.sport, row.year, row.value)
        if full in seen:
            errors.append(f"{where}: duplicate of an earlier row")
            continue
        seen.add(full)
        if row.rule in _RULE_SINGLE_VALUED:
            key = (row.rule, row.school, row.sport)
        elif row.rule == "form_through":
            key = (row.rule, row.school, row.sport, row.year)
        else:
            key = None
        if key is not None:
            if key in unique:
                errors.append(f"{where}: conflicts with line {unique[key]} (same {row.rule} key)")
                continue
            unique[key] = row.line
        rows.append(row)
    through_to = {}
    for r in rows:
        if r.rule == "form_through":
            through_to[(r.school, r.sport)] = max(through_to.get((r.school, r.sport), 0), r.year)
    for r in rows:
        if r.rule == "form_from" and r.year <= through_to.get((r.school, r.sport), 0):
            errors.append(f"line {r.line}: form_from {r.year} overlaps the form_through rows for {r.school} {r.sport} (they run to {through_to[(r.school, r.sport)]})")
    return rows, errors


def _build_rule_tables(rows):
    t = {name: ({} if name in ("SPORT_SLUG_ALIASES", "SCHOOL_PREFERS_DASH_YEAR", "SCHOOL_FORM_THROUGH", "PROGRAM_FIRST_YEAR",
                               "KNOWN_UNAVAILABLE", "SCHOOL_SLUG_OVERRIDES", "SCHOOL_FORM_FROM") else set()) for name in _RULE_TABLE_NAMES}
    for r in rows:
        pair = (r.school, r.sport)
        if r.rule == "slug_alias":
            t["SPORT_SLUG_ALIASES"].setdefault(r.sport, []).append(r.value)  # file order is the try order
        elif r.rule == "spring_season":
            t["SPRING_SEASON_SPORTS"].add(r.sport)
        elif r.rule == "skip_bare_year":
            t["SKIP_BARE_YEAR_SPORTS"].add(r.sport)
        elif r.rule == "prefer_bare":
            t["SCHOOL_PREFERS_BARE_YEAR"].add(pair)
        elif r.rule == "prefer_dash":
            t["SCHOOL_PREFERS_DASH_YEAR"][pair] = r.year
        elif r.rule == "form_through":
            t["SCHOOL_FORM_THROUGH"].setdefault(pair, []).append((r.year, r.value))
        elif r.rule == "form_from":
            t["SCHOOL_FORM_FROM"][pair] = (r.year, r.value)
        elif r.rule == "missing_season":
            t["KNOWN_MISSING_SEASONS"].add((r.school, r.sport, r.year))
        elif r.rule == "first_year":
            t["PROGRAM_FIRST_YEAR"][pair] = r.year
        elif r.rule == "unavailable":
            t["KNOWN_UNAVAILABLE"][pair] = r.note
        elif r.rule == "slug_override":
            t["SCHOOL_SLUG_OVERRIDES"][pair] = r.value
        elif r.rule == "combined_page":
            t["KNOWN_COMBINED_PAGE"].add(pair)
        elif r.rule == "cleanup_exempt":
            t["NEUTRAL_ENTRY_CLEANUP_EXEMPT"].add(r.sport)
    # "First matching entry wins" depends on season order, so never trust row order in the file.
    for pair, entries in t["SCHOOL_FORM_THROUGH"].items():
        t["SCHOOL_FORM_THROUGH"][pair] = sorted(entries)
    return t


def load_site_rules(path=RULES_PATH, valid_schools=None):
    """Read, check and build the rule tables. Raises ValueError listing every bad row at once."""
    valid_schools = set(bases_df["school"]) if valid_schools is None else valid_schools
    rows, errors = _check_rules(_read_rules(path), valid_schools)
    if errors:
        raise ValueError(f"{path} has {len(errors)} problem(s):\n  " + "\n  ".join(errors))
    return _build_rule_tables(rows)


_rule_tables = None


def __getattr__(name):
    """config.KNOWN_UNAVAILABLE and the other rule tables load site_rules.csv on first use."""
    global _rule_tables
    if name in _RULE_TABLE_NAMES:
        if _rule_tables is None:
            _rule_tables = load_site_rules()
        return _rule_tables[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
